#name = "svepomocizahubicku.cesanom.workers.dev"
name = "test.cesanom.workers.dev"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
#binding = "DB"  # název v kódu (env.DB)
#database_name = "svepomocizahubicku-db"
#database_id = "405f9bab-fac5-4aa6-bbff-ddc72cf38444"  # ID z Cloudflare dashboardu po vytvoření DB
binding = "DB"  # název v kódu (env.DB)
database_name = "prod-d1-tutorial"
database_id = "4f63c9fa-72cd-4311-9428-c584f354ae9c"  # ID z Cloudflare dashboardu po vytvoření DB
